-- AlterTable
ALTER TABLE `message_flows_steps` MODIFY `type` ENUM('CONDITION', 'QUERY', 'ROUTER', 'ASSIGN', 'CHECK_AVAILABLE_USERS', 'CHECK_USER_ONLINE', 'CHECK_LOALTY', 'CHECK_ONLY_ADMIN', 'SEND_TO_ADMIN', 'SEND_TO_SECTOR_USER', 'SEND_TO_SPECIFIC_USER', 'CHECK_CUSTOMER_CAMPAIGN_TYPE') NOT NULL;
