CREATE TABLE `pipeline_enrollment_outbox` (
  `id` VARCHAR(191) NOT NULL,
  `idempotency_key` VARCHAR(191) NOT NULL,
  `instance` VARCHAR(30) NOT NULL,
  `source_type` ENUM('READY_MESSAGE', 'WHATSAPP_TEMPLATE') NOT NULL,
  `source_key` VARCHAR(191) NOT NULL,
  `message_id` INTEGER NOT NULL,
  `contact_id` INTEGER NULL,
  `customer_id` INTEGER NULL,
  `status` ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED') NOT NULL DEFAULT 'PENDING',
  `retry_count` INTEGER NOT NULL DEFAULT 0,
  `error` TEXT NULL,
  `locked_until` DATETIME(3) NULL,
  `locked_by` VARCHAR(191) NULL,
  `processing_started_at` DATETIME(3) NULL,
  `next_attempt_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `completed_at` DATETIME(3) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  UNIQUE INDEX `pipeline_enrollment_outbox_idempotency_key_key` (`idempotency_key`),
  INDEX `pipeline_enrollment_outbox_status_next_attempt_at_idx` (`status`, `next_attempt_at`),
  INDEX `pipeline_enrollment_outbox_locked_until_idx` (`locked_until`),
  INDEX `pipeline_enrollment_outbox_instance_message_id_idx` (`instance`, `message_id`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
