// Contract from the user-supplied Karsten probe, 2026-09-20. No row data.
export const legacyContract = {
  wpp_contacts: {
    columns: [
      {"name":"id","type":"int(11)","nullable":"NO","charset":null,"collation":null,"extra":""},
      {"name":"instance","type":"varchar(255)","nullable":"NO","charset":"utf8","collation":"utf8_general_ci","extra":""},
      {"name":"name","type":"varchar(255)","nullable":"NO","charset":"utf8","collation":"utf8_general_ci","extra":""},
      {"name":"phone","type":"varchar(50)","nullable":"NO","charset":"utf8","collation":"utf8_general_ci","extra":""},
      {"name":"customer_id","type":"int(11)","nullable":"YES","charset":null,"collation":null,"extra":""},
      {"name":"is_deleted","type":"tinyint(1)","nullable":"NO","charset":null,"collation":null,"extra":""},
    ],
    uniqueIndexes: [{"primary":true,"columns":["id"]},{"primary":false,"columns":["instance","phone"]}],
  },
  wpp_contact_sectors: {
    columns: [
      {"name":"contact_id","type":"int(11)","nullable":"NO","charset":null,"collation":null,"extra":""},
      {"name":"sector_id","type":"int(11)","nullable":"NO","charset":null,"collation":null,"extra":""},
    ],
    uniqueIndexes: [{"primary":true,"columns":["contact_id","sector_id"]}],
  },
  wpp_chats: {
    columns: [
      {"name":"id","type":"int(11)","nullable":"NO","charset":null,"collation":null,"extra":"auto_increment"},
      {"name":"original_id","type":"int(11)","nullable":"NO","charset":null,"collation":null,"extra":""},
      {"name":"instance","type":"varchar(255)","nullable":"NO","charset":"utf8","collation":"utf8_general_ci","extra":""},
      {"name":"type","type":"varchar(50)","nullable":"NO","charset":"utf8","collation":"utf8_general_ci","extra":""},
      {"name":"avatar_url","type":"mediumtext","nullable":"YES","charset":"utf8","collation":"utf8_general_ci","extra":""},
      {"name":"user_id","type":"int(11)","nullable":"YES","charset":null,"collation":null,"extra":""},
      {"name":"contact_id","type":"int(11)","nullable":"YES","charset":null,"collation":null,"extra":""},
      {"name":"sector_id","type":"int(11)","nullable":"YES","charset":null,"collation":null,"extra":""},
      {"name":"bot_id","type":"int(11)","nullable":"YES","charset":null,"collation":null,"extra":""},
      {"name":"started_at","type":"datetime","nullable":"YES","charset":null,"collation":null,"extra":""},
      {"name":"finished_at","type":"datetime","nullable":"YES","charset":null,"collation":null,"extra":""},
      {"name":"finished_by","type":"int(11)","nullable":"YES","charset":null,"collation":null,"extra":""},
      {"name":"result_id","type":"int(11)","nullable":"YES","charset":null,"collation":null,"extra":""},
      {"name":"is_finished","type":"tinyint(1)","nullable":"NO","charset":null,"collation":null,"extra":""},
      {"name":"is_schedule","type":"tinyint(1)","nullable":"NO","charset":null,"collation":null,"extra":""},
    ],
    uniqueIndexes: [{"primary":false,"columns":["original_id"]},{"primary":true,"columns":["id"]}],
  },
  wpp_messages: {
    columns: [
      {"name":"id","type":"int(11)","nullable":"NO","charset":null,"collation":null,"extra":""},
      {"name":"instance","type":"varchar(255)","nullable":"NO","charset":"utf8","collation":"utf8_general_ci","extra":""},
      {"name":"wwebjs_id","type":"varchar(255)","nullable":"YES","charset":"utf8","collation":"utf8_general_ci","extra":""},
      {"name":"wwebjs_id_stanza","type":"varchar(255)","nullable":"YES","charset":"utf8","collation":"utf8_general_ci","extra":""},
      {"name":"waba_id","type":"varchar(255)","nullable":"YES","charset":"utf8","collation":"utf8_general_ci","extra":""},
      {"name":"gupshup_id","type":"varchar(255)","nullable":"YES","charset":"utf8","collation":"utf8_general_ci","extra":""},
      {"name":"gupshup_request_id","type":"varchar(255)","nullable":"YES","charset":"utf8","collation":"utf8_general_ci","extra":""},
      {"name":"from","type":"varchar(255)","nullable":"NO","charset":"utf8","collation":"utf8_general_ci","extra":""},
      {"name":"to","type":"varchar(255)","nullable":"NO","charset":"utf8","collation":"utf8_general_ci","extra":""},
      {"name":"type","type":"varchar(50)","nullable":"NO","charset":"utf8","collation":"utf8_general_ci","extra":""},
      {"name":"quoted_id","type":"int(11)","nullable":"YES","charset":null,"collation":null,"extra":""},
      {"name":"chat_id","type":"int(11)","nullable":"YES","charset":null,"collation":null,"extra":""},
      {"name":"contact_id","type":"int(11)","nullable":"YES","charset":null,"collation":null,"extra":""},
      {"name":"is_forwarded","type":"tinyint(1)","nullable":"NO","charset":null,"collation":null,"extra":""},
      {"name":"is_edited","type":"tinyint(1)","nullable":"NO","charset":null,"collation":null,"extra":""},
      {"name":"body","type":"longtext","nullable":"NO","charset":"utf8","collation":"utf8_general_ci","extra":""},
      {"name":"timestamp","type":"varchar(64)","nullable":"NO","charset":"utf8","collation":"utf8_general_ci","extra":""},
      {"name":"sent_at","type":"datetime","nullable":"NO","charset":null,"collation":null,"extra":""},
      {"name":"status","type":"varchar(50)","nullable":"NO","charset":"utf8","collation":"utf8_general_ci","extra":""},
      {"name":"file_id","type":"int(11)","nullable":"YES","charset":null,"collation":null,"extra":""},
      {"name":"file_name","type":"longtext","nullable":"YES","charset":"utf8","collation":"utf8_general_ci","extra":""},
      {"name":"file_type","type":"varchar(255)","nullable":"YES","charset":"utf8","collation":"utf8_general_ci","extra":""},
      {"name":"file_size","type":"varchar(255)","nullable":"YES","charset":"utf8","collation":"utf8_general_ci","extra":""},
      {"name":"user_id","type":"int(11)","nullable":"YES","charset":null,"collation":null,"extra":""},
      {"name":"billing_category","type":"varchar(255)","nullable":"YES","charset":"utf8","collation":"utf8_general_ci","extra":""},
      {"name":"client_id","type":"int(11)","nullable":"YES","charset":null,"collation":null,"extra":""},
    ],
    uniqueIndexes: [{"primary":true,"columns":["id"]},{"primary":false,"columns":["gupshup_id"]},{"primary":false,"columns":["waba_id"]},{"primary":false,"columns":["wwebjs_id"]},{"primary":false,"columns":["wwebjs_id_stanza"]}],
  },
  wpp_schedules: {
    columns: [
      {"name":"id","type":"int(11)","nullable":"NO","charset":null,"collation":null,"extra":""},
      {"name":"instance","type":"varchar(255)","nullable":"NO","charset":"utf8","collation":"utf8_general_ci","extra":""},
      {"name":"description","type":"text","nullable":"YES","charset":"utf8","collation":"utf8_general_ci","extra":""},
      {"name":"contact_id","type":"int(11)","nullable":"NO","charset":null,"collation":null,"extra":""},
      {"name":"chat_id","type":"int(11)","nullable":"YES","charset":null,"collation":null,"extra":""},
      {"name":"scheduled_at","type":"datetime","nullable":"NO","charset":null,"collation":null,"extra":""},
      {"name":"schedule_date","type":"datetime","nullable":"NO","charset":null,"collation":null,"extra":""},
      {"name":"scheduled_by","type":"int(11)","nullable":"NO","charset":null,"collation":null,"extra":""},
      {"name":"scheduled_for","type":"int(11)","nullable":"NO","charset":null,"collation":null,"extra":""},
      {"name":"sector_id","type":"int(11)","nullable":"YES","charset":null,"collation":null,"extra":""},
    ],
    uniqueIndexes: [{"primary":true,"columns":["id"]}],
  },
} as const;
