-- Retrofit definitivo para classificação de respostas da pesquisa de satisfação.
-- Objetivo:
-- 1) Adicionar colunas canônicas em w_questionarios_respostas (idempotente)
-- 2) Backfill retroativo por padrões (inclui variações com charset quebrado)
-- 3) Preparar consulta por chave estável (QUESTION_KEY)

SET @table_name := 'w_questionarios_respostas';

SET @sql := (
  SELECT IF(
    COUNT(*) = 0,
    'ALTER TABLE w_questionarios_respostas ADD COLUMN QUESTION_KEY VARCHAR(32) NULL AFTER PERGUNTA',
    'SELECT 1'
  )
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @table_name AND COLUMN_NAME = 'QUESTION_KEY'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql := (
  SELECT IF(
    COUNT(*) = 0,
    'ALTER TABLE w_questionarios_respostas ADD COLUMN SURVEY_VERSION VARCHAR(32) NULL AFTER QUESTION_KEY',
    'SELECT 1'
  )
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @table_name AND COLUMN_NAME = 'SURVEY_VERSION'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql := (
  SELECT IF(
    COUNT(*) = 0,
    'ALTER TABLE w_questionarios_respostas ADD COLUMN QUESTION_INDEX TINYINT NULL AFTER SURVEY_VERSION',
    'SELECT 1'
  )
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @table_name AND COLUMN_NAME = 'QUESTION_INDEX'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql := (
  SELECT IF(
    COUNT(*) = 0,
    'ALTER TABLE w_questionarios_respostas ADD COLUMN SCALE_MIN TINYINT NULL AFTER QUESTION_INDEX',
    'SELECT 1'
  )
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @table_name AND COLUMN_NAME = 'SCALE_MIN'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql := (
  SELECT IF(
    COUNT(*) = 0,
    'ALTER TABLE w_questionarios_respostas ADD COLUMN SCALE_MAX TINYINT NULL AFTER SCALE_MIN',
    'SELECT 1'
  )
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @table_name AND COLUMN_NAME = 'SCALE_MAX'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql := (
  SELECT IF(
    COUNT(*) = 0,
    'ALTER TABLE w_questionarios_respostas ADD COLUMN IS_NOT_APPLICABLE TINYINT(1) NULL AFTER SCALE_MAX',
    'SELECT 1'
  )
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @table_name AND COLUMN_NAME = 'IS_NOT_APPLICABLE'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql := (
  SELECT IF(
    COUNT(*) = 0,
    'ALTER TABLE w_questionarios_respostas ADD COLUMN CLASSIFICATION_CONFIDENCE DECIMAL(4,3) NULL AFTER IS_NOT_APPLICABLE',
    'SELECT 1'
  )
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @table_name AND COLUMN_NAME = 'CLASSIFICATION_CONFIDENCE'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

START TRANSACTION;

UPDATE w_questionarios_respostas
SET IS_NOT_APPLICABLE = CASE WHEN NOTA = 99 THEN 1 ELSE 0 END
WHERE IS_NOT_APPLICABLE IS NULL;

UPDATE w_questionarios_respostas
SET
  QUESTION_KEY = 'q1',
  QUESTION_INDEX = COALESCE(QUESTION_INDEX, 1),
  CLASSIFICATION_CONFIDENCE = COALESCE(CLASSIFICATION_CONFIDENCE, 0.990)
WHERE QUESTION_KEY IS NULL
  AND (
    LOWER(PERGUNTA) LIKE '%qualidade%'
    OR LOWER(PERGUNTA) LIKE '%inovação%'
    OR LOWER(PERGUNTA) LIKE '%inovacao%'
    OR LOWER(PERGUNTA) LIKE '%instalação e uso%'
    OR LOWER(PERGUNTA) LIKE '%instalacao e uso%'
    OR LOWER(PERGUNTA) LIKE '%inovaÃ§Ã£o%'
    OR LOWER(PERGUNTA) LIKE '%influencia sua decis%'
  );

UPDATE w_questionarios_respostas
SET
  QUESTION_KEY = 'q2',
  QUESTION_INDEX = COALESCE(QUESTION_INDEX, 2),
  CLASSIFICATION_CONFIDENCE = COALESCE(CLASSIFICATION_CONFIDENCE, 0.990)
WHERE QUESTION_KEY IS NULL
  AND (
    LOWER(PERGUNTA) LIKE '%assistência técnica%'
    OR LOWER(PERGUNTA) LIKE '%assistencia tecnica%'
    OR LOWER(PERGUNTA) LIKE '%assistÃªncia tÃ©cnica%'
    OR LOWER(PERGUNTA) LIKE '%tempo de resposta%'
  );

UPDATE w_questionarios_respostas
SET
  QUESTION_KEY = 'q3',
  QUESTION_INDEX = COALESCE(QUESTION_INDEX, 3),
  CLASSIFICATION_CONFIDENCE = COALESCE(CLASSIFICATION_CONFIDENCE, 0.980)
WHERE QUESTION_KEY IS NULL
  AND (
    LOWER(PERGUNTA) LIKE '%nossa equipe%'
    OR LOWER(PERGUNTA) LIKE '%funcionários e representantes%'
    OR LOWER(PERGUNTA) LIKE '%funcionarios e representantes%'
    OR LOWER(PERGUNTA) LIKE '%funcionÃ¡rios e representantes%'
    OR LOWER(PERGUNTA) LIKE '%atendimento prestado pela nossa equipe%'
  );

UPDATE w_questionarios_respostas
SET
  QUESTION_KEY = 'q4',
  QUESTION_INDEX = COALESCE(QUESTION_INDEX, 4),
  CLASSIFICATION_CONFIDENCE = COALESCE(CLASSIFICATION_CONFIDENCE, 0.980)
WHERE QUESTION_KEY IS NULL
  AND (
    LOWER(PERGUNTA) LIKE '%de forma geral%'
    OR LOWER(PERGUNTA) LIKE '%quão satisfeito%'
    OR LOWER(PERGUNTA) LIKE '%quao satisfeito%'
    OR LOWER(PERGUNTA) LIKE '%quÃ£o satisfeito%'
    OR LOWER(PERGUNTA) LIKE '%nível de satisfação%'
    OR LOWER(PERGUNTA) LIKE '%nivel de satisfacao%'
    OR LOWER(PERGUNTA) LIKE '%nÃ­vel de satisfaÃ§Ã£o%'
    OR LOWER(PERGUNTA) LIKE '%quão prestativa%'
    OR LOWER(PERGUNTA) LIKE '%quao prestativa%'
    OR LOWER(PERGUNTA) LIKE '%quÃ£o prestativa%'
  );

UPDATE w_questionarios_respostas
SET
  SURVEY_VERSION = CASE
    WHEN LOWER(PERGUNTA) LIKE '%0 a 5%' OR (NOTA BETWEEN 0 AND 5 AND NOTA <> 99) THEN 'EXA_V1_0_5'
    WHEN LOWER(PERGUNTA) LIKE '%1 a 10%' OR LOWER(PERGUNTA) LIKE '%digite de 1 a 10%' OR (NOTA BETWEEN 1 AND 10) THEN 'EXA_V2_1_10'
    ELSE SURVEY_VERSION
  END,
  SCALE_MIN = CASE
    WHEN LOWER(PERGUNTA) LIKE '%0 a 5%' OR (NOTA BETWEEN 0 AND 5 AND NOTA <> 99) THEN 0
    WHEN LOWER(PERGUNTA) LIKE '%1 a 10%' OR LOWER(PERGUNTA) LIKE '%digite de 1 a 10%' OR (NOTA BETWEEN 1 AND 10) THEN 1
    ELSE SCALE_MIN
  END,
  SCALE_MAX = CASE
    WHEN LOWER(PERGUNTA) LIKE '%0 a 5%' OR (NOTA BETWEEN 0 AND 5 AND NOTA <> 99) THEN 5
    WHEN LOWER(PERGUNTA) LIKE '%1 a 10%' OR LOWER(PERGUNTA) LIKE '%digite de 1 a 10%' OR (NOTA BETWEEN 1 AND 10) THEN 10
    ELSE SCALE_MAX
  END
WHERE SURVEY_VERSION IS NULL OR SCALE_MIN IS NULL OR SCALE_MAX IS NULL;

SET @sql := (
  SELECT IF(
    COUNT(*) = 0,
    'CREATE INDEX IDX_W_QR_QUESTION_KEY ON w_questionarios_respostas (QUESTION_KEY)',
    'SELECT 1'
  )
  FROM INFORMATION_SCHEMA.STATISTICS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @table_name AND INDEX_NAME = 'IDX_W_QR_QUESTION_KEY'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql := (
  SELECT IF(
    COUNT(*) = 0,
    'CREATE INDEX IDX_W_QR_ATENDIMENTO_KEY ON w_questionarios_respostas (CODIGO_ATENDIMENTO, QUESTION_KEY)',
    'SELECT 1'
  )
  FROM INFORMATION_SCHEMA.STATISTICS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @table_name AND INDEX_NAME = 'IDX_W_QR_ATENDIMENTO_KEY'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

COMMIT;

SELECT
  QUESTION_KEY,
  COUNT(*) AS total
FROM w_questionarios_respostas
GROUP BY QUESTION_KEY
ORDER BY total DESC;
